<#
Forever SV Bridge  v0.2  -  addon settings that survive the WoW: Forever beta.

The beta client writes WTF\...\SavedVariables\*.lua but rarely loads them back
(most sessions start from defaults). It does load addon Lua files, so this
copies the saved files into a tiny addon (!!ForeverSVBridge) that sorts first
and executes them as code, recreating every addon's globals before the real
addons load. Account-wide files are copied as they are; per-character files
are wrapped per character and the right set runs for whoever logs in.

EllesmereUI 9.2.1+ knows about the bug (EllesmereUI.FOREVER_SV_BUG) and nils
its stores at logout, which would starve this bridge; when that suite is
installed the addon's first file forces the switch to false via a metatable
on the EllesmereUI table (no EllesmereUI file is edited).

One-line install (install.ps1 downloads this file to %LOCALAPPDATA%\ForeverSVBridge
and runs it: registers a hidden logon task that keeps it watching, starts it now):

    irm https://sv.melting.lol/install.ps1 | iex

This file keeps its UTF-8 BOM on purpose: Windows PowerShell reads a BOM-less
file as ANSI and the box-drawing art then breaks the parser (0x94 = a quote).

Installed:   forever_sv_bridge.ps1 -Watch [-GamePath <_classic_beta_>]   run the watcher here
             forever_sv_bridge.ps1 -Uninstall                             remove task, addon, install dir
Writes only Interface\AddOns\!!ForeverSVBridge in the game folder and its own install dir.
#>
param([switch]$Watch, [switch]$Uninstall, [string]$GamePath)

$Version    = "0.2"
$TaskName   = "ForeverSVBridge"
$AddonName  = "!!ForeverSVBridge"
$Quiet      = 1.0   # seconds a file must sit still before it is copied
$Self       = $PSCommandPath                       # install.ps1 (the irm | iex bootstrap) downloads this file and runs it
$InstallDir = "$env:LOCALAPPDATA\ForeverSVBridge"
$Log        = "$InstallDir\forever_sv_bridge.log"

$HeadLua = @'
-- Generated by forever_sv_bridge.ps1 VERSION - do not edit.
ForeverSVBridge = { char = {} }
'@

$LoaderLua = @'
-- Per-character seeds: each WTF\<realm>\<char>\SavedVariables file was wrapped
-- as ForeverSVBridge.char[<char folder>][<addon>] = function() ... end. Run
-- the set for the character logging in. The WTF folder is the character name
-- with spaces turned into dashes; an account with one character needs no match.
-- ponytail: realm ignored (its folder name is unreliable); same name on two realms -> last mirrored wins
local me = UnitName("player") or ""
local chars, n, only = ForeverSVBridge.char, 0, nil
for _, v in pairs(chars) do n = n + 1; only = v end
local pick = chars[me] or chars[(me:gsub("%s", "-"))] or (n == 1 and only) or nil
if pick then for _, fn in pairs(pick) do fn() end end
'@

$EuiLua = @'
-- EllesmereUI shim. EllesmereUI_Lite.lua does `EllesmereUI = EllesmereUI or {}`
-- then `EllesmereUI.FOREVER_SV_BUG = EllesmereUI.IS_FOREVER`. We own the table
-- first, so the assignment hits __newindex and lands as false: the logout
-- store killer never registers and settings reach WTF for this bridge.
EllesmereUI = setmetatable({}, { __newindex = function(t, k, v)
    if k == "FOREVER_SV_BUG" then v = false end
    rawset(t, k, v)
end })

-- Self-check, decided where it can be seen: at EllesmereUI's ADDON_LOADED the
-- client has applied that addon's SavedVariables. Same table as we seeded =
-- the client loaded nothing (the bug, the normal case). nil = the client
-- executed a store the suite nil'd at an earlier logout; the seed is the only
-- copy, put it back before Lite captures the table. A different table = the
-- client fed its own copy back and the bridge is idle this session; say so,
-- touch nothing. Never nil anything: a wrong guess must cost nothing.
local seeded
local f = CreateFrame("Frame")
f:RegisterEvent("ADDON_LOADED")
f:SetScript("OnEvent", function(self, _, name)
    if name == "!!ForeverSVBridge" then seeded = EllesmereUIDB; return end
    if name ~= "EllesmereUI" then return end
    self:UnregisterEvent("ADDON_LOADED")
    if EllesmereUIDB == nil then
        EllesmereUIDB = seeded
    elseif seeded and EllesmereUIDB ~= seeded then
        C_Timer.After(5, function()
            print("|cffff8800ForeverSVBridge:|r the client loaded EllesmereUI's settings by itself this session. If this shows every login the bug is fixed: run forever_sv_bridge.ps1 -Uninstall.")
        end)
    end
end)
'@

# ----------------------------------------------------------------- styling ---
$Esc = [char]27
$VT  = $Host.UI.SupportsVirtualTerminal -or $env:WT_SESSION
function Hue($r, $g, $b) { if ($VT) { "$Esc[38;2;$r;$g;${b}m" } else { "" } }
$cT = Hue 90 200 190; $cB = Hue 38 120 150; $cG = Hue 214 180 120; $cS = Hue 170 170 170; $cD = Hue 135 135 135; $cW = Hue 225 225 225
$cX = if ($VT) { "$Esc[0m" } else { "" }

function Cols { try { $w = $Host.UI.RawUI.WindowSize.Width; if ($w -gt 0) { return $w } } catch {}; 80 }   # hidden task / redirected: 80

function Rule($title) {   # no wider than the compact banner (55) or the window: survives a later shrink down to that
    $w = [Math]::Min(55, (Cols) - 1)
    if ($title) { Write-Host ("  $cD╶── $cW$title $cD" + ("─" * [Math]::Max(4, $w - 8 - $title.Length)) + "╴$cX") }
    else        { Write-Host ("  $cD" + ("─" * ($w - 2)) + $cX) }
}

function Center($text, $width) { $l = [Math]::Max(0, [int](($width - $text.Length) / 2)); (" " * $l + $text).PadRight($width) }

function Show-Banner([switch]$Small, [switch]$Compact) {
    if (-not $Small -and (Cols) -lt $(if ($Compact) { 56 } else { 65 })) { $Small = $true }   # too narrow for the picture
    if ($Small) {
        Write-Host ("  $cT[ SV ]$cS ═══════ SavedVariables ═══════$cB╡ $cG`W$cB ╞$cX")
        return
    }
    if ($Compact) {   # watcher: 5 rows, deck enters both glyphs
        $left  = @(" ╭───────╮", " │ ┌───┐ │", " │ │SV │ ├", " │ ▐███▌ │", " ╰───────╯")
        $mid   = @("                              ", "   ╷                      ╷   ", "═══╪══════════════════════╪═══",
                   "   ║                      ║   ", " ~~╨~~~~~~~~~~~~~~~~~~~~~~╨~~ ")
        $right = @("     ◆       ", " ╭───┴───╮   ", "═╡ ∞ W ∞ ├─◆ ", " ╰───┬───╯   ", "     ◆       ")
    } else {          # installer: 7 rows, suspension bridge
        $left  = @(" ╭──────────╮", " │ ┌──────┐ │", " │ │  SV  │ │", " │ └──────┘ │", " │          ├", " │  ▐████▌  │", " ╰──────────╯")
        $mid   = @("                                    ", "         │                │         ", "      ╭──┼──╮          ╭──┼──╮      ",
                   "   ╭──╯  │  ╰──────────╯  │  ╰──╮   ", "═══╧═════╧════════════════╧═════╧═══", "   ║     ║                ║     ║   ",
                   " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
        $right = @("             ", "     ◆       ", " ╭───┴───╮   ", " │       │   ", "═╡ ∞ W ∞ ├─◆ ", " ╰───┬───╯   ", "     ◆       ")
    }
    Write-Host ""
    for ($i = 0; $i -lt $left.Count; $i++) {
        $w = $right[$i] -replace '([W◆∞])', "$cG`$1$cB" -replace '^═', "$cS═$cB"
        Write-Host ("  $cT" + $left[$i] + $cS + ($mid[$i] -replace '~', "$cD~$cS") + $cB + $w + $cX)
    }
    Write-Host ("  $cT" + (Center "SAVED VARS" $left[0].Length) + $cD + (Center "Forever SV Bridge v$Version" $mid[0].Length) + $cG + (Center "WoW: FOREVER" $right[0].Length) + $cX)
    Write-Host ""
}

# ---------------------------------------------------------------- watcher ---
function Say($msg) {
    $line = "{0} {1}" -f (Get-Date -Format "HH:mm:ss"), $msg
    Write-Host "  $cD$($line.Substring(0, 8))$cX $msg"
    New-Item -ItemType Directory -Force -Path (Split-Path $Log) | Out-Null
    Add-Content -LiteralPath $Log -Value $line
}

function Use-GameDir($dir) {   # every path below hangs off the game folder
    $script:Root   = $dir
    $script:Addons = "$dir\Interface\AddOns"
    $script:Seed   = "$script:Addons\$AddonName"
}

function Get-AccountDir {
    # ponytail: several accounts -> the one whose files changed last; one seed addon cannot serve two
    $dirs = Get-ChildItem "$Root\WTF\Account\*\SavedVariables" -Directory -ErrorAction SilentlyContinue |
        Where-Object { Get-ChildItem -LiteralPath $_.FullName -Filter *.lua | Where-Object Name -notlike "Blizzard_*" }
    if ($dirs) {
        ($dirs | Sort-Object { (Get-ChildItem -LiteralPath $_.FullName -Filter *.lua | Measure-Object LastWriteTime -Maximum).Maximum } |
            Select-Object -Last 1).Parent.FullName
    }
}

function Get-Sources($acct) {
    # account-wide files, then per-character ones (WTF\Account\<acct>\<realm>\<char>\SavedVariables)
    $lua = { $_.Extension -eq ".lua" -and $_.Name -notlike "Blizzard_*" }
    @(Get-ChildItem "$acct\SavedVariables\*" -File | Where-Object $lua | ForEach-Object {
        @{ Src = $_.FullName; Rel = "acct\$($_.Name)"; Char = $null } }) +
    @(Get-ChildItem "$acct\*\*\SavedVariables\*" -File | Where-Object $lua | ForEach-Object {
        @{ Src = $_.FullName; Rel = "char\$($_.Directory.Parent.Name)\$($_.Name)"; Char = $_.Directory.Parent.Name } })
}

function Test-Valid($path) {
    # balanced braces and at least one non-empty table ("X = nil" / "X = {}" would only wipe a good seed)
    $b = [IO.File]::ReadAllText($path)
    ($b.Split('{').Count -eq $b.Split('}').Count) -and ($b -match '= \{\s*[^\s}]')
}

function Write-Seed($s) {
    $dst = "$Seed\seeds\$($s.Rel)"
    New-Item -ItemType Directory -Force -Path (Split-Path $dst) | Out-Null
    if (-not $s.Char) { Copy-Item -LiteralPath $s.Src -Destination $dst -Force; return }
    # ponytail: the wrapped body shares one function's Lua limits with the original chunk, same ceiling
    $k = $s.Char.Replace('\', '\\').Replace('"', '\"'); $a = [IO.Path]::GetFileNameWithoutExtension($s.Src)
    $body = [IO.File]::ReadAllText($s.Src)
    [IO.File]::WriteAllText($dst, "ForeverSVBridge.char[`"$k`"] = ForeverSVBridge.char[`"$k`"] or {}`nForeverSVBridge.char[`"$k`"][`"$a`"] = function()`n$body`nend`n")
}

function Write-Addon {
    New-Item -ItemType Directory -Force -Path "$Seed\seeds" | Out-Null
    $files = @("Bridge_Head.lua")
    [IO.File]::WriteAllText("$Seed\Bridge_Head.lua", $HeadLua.Replace("VERSION", $Version).Replace("`r`n", "`n"))
    if (Test-Path -LiteralPath "$Addons\EllesmereUI") {
        [IO.File]::WriteAllText("$Seed\Bridge_EllesmereUI.lua", $EuiLua.Replace("`r`n", "`n"))
        $files += "Bridge_EllesmereUI.lua"
    }
    $files += Get-ChildItem "$Seed\seeds" -Recurse -File | Sort-Object { $_.FullName -notlike "*\acct\*" }, FullName |
        ForEach-Object { $_.FullName.Substring($Seed.Length + 1) }
    [IO.File]::WriteAllText("$Seed\Bridge_Loader.lua", $LoaderLua.Replace("`r`n", "`n"))
    $files += "Bridge_Loader.lua"
    $toc = @("## Interface: 16001", "## Title: $AddonName", "## Notes: SavedVariables bridge for the Forever beta - generated by forever_sv_bridge.ps1, do not edit",
             "## Version: $Version", "") + $files
    [IO.File]::WriteAllText("$Seed\$AddonName.toc", ($toc -join "`r`n") + "`r`n")
}

function Sync-Seeds($acct, $state) {
    $changed = $false
    foreach ($s in Get-Sources $acct) {
        $m = (Get-Item -LiteralPath $s.Src).LastWriteTimeUtc
        if ($state[$s.Rel] -eq $m -or ((Get-Date).ToUniversalTime() - $m).TotalSeconds -lt $Quiet -or -not (Test-Valid $s.Src)) { continue }
        Write-Seed $s
        $state[$s.Rel] = $m
        $changed = $true
        Say ("seeded {0} {1} bytes" -f $s.Rel, (Get-Item -LiteralPath $s.Src).Length)
    }
    $changed
}

function Start-Watch {
    Use-GameDir $(if ($GamePath) { $GamePath } else { Find-BetaDir })
    Show-Banner -Compact
    Rule "watching"
    Say "bridge $Version watching $Root (Ctrl+C to stop)"
    $acct = $null
    while (-not $acct) {
        $acct = Get-AccountDir
        if (-not $acct) { Say "no WTF\Account\*\SavedVariables yet - log in once, I'll wait"; Start-Sleep 30 }
    }
    Write-Addon
    $state = @{}
    while ($true) {
        if (-not (Test-Path -LiteralPath "$Seed\Bridge_Head.lua")) { Say "addon missing - rebuilding"; $state = @{} }
        if (Sync-Seeds $acct $state) { Write-Addon }   # the toc lists whatever seeds exist
        # ponytail: slow poll while the game is closed; a logout write still lands within 5 s
        if (Get-Process WowB -ErrorAction SilentlyContinue) { Start-Sleep -Milliseconds 250 } else { Start-Sleep 5 }
    }
}

# -------------------------------------------------------------- installer ---
function Find-BetaDir {
    $bases = @()
    $reg = Get-ItemProperty "HKLM:\SOFTWARE\WOW6432Node\Blizzard Entertainment\World of Warcraft" -ErrorAction SilentlyContinue
    if ($reg.InstallPath) { $bases += Split-Path -Parent $reg.InstallPath.TrimEnd('\') }
    $db = "$env:ProgramData\Battle.net\Agent\product.db"
    if (Test-Path $db) {
        $txt = [Text.Encoding]::UTF8.GetString([IO.File]::ReadAllBytes($db))
        $bases += [regex]::Matches($txt, '[A-Za-z]:[\\/][^\x00"]*?World of Warcraft') | ForEach-Object { $_.Value -replace '/', '\' }
    }
    $bases += "${env:ProgramFiles(x86)}\World of Warcraft", "$env:ProgramFiles\World of Warcraft"
    foreach ($b in $bases | Select-Object -Unique) {
        if (Test-Path -LiteralPath "$b\_classic_beta_\WowB.exe") { return "$b\_classic_beta_" }
    }
    do { $p = (Read-Host "Where is your World of Warcraft\_classic_beta_ folder?").Trim('"') } until (Test-Path -LiteralPath "$p\WowB.exe")
    $p
}

function Install-Bridge {
    Show-Banner
    Rule "install"
    $beta = if ($GamePath) { $GamePath } else { Find-BetaDir }
    $dst  = "$InstallDir\forever_sv_bridge.ps1"
    Write-Host "  $cW game folder $cD│$cX $beta"
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    if ($Self -ne $dst) { Copy-Item -LiteralPath $Self -Destination $dst -Force }
    Write-Host "  $cW installed   $cD│$cX $dst"

    $action  = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$dst`" -Watch -GamePath `"$beta`""
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit 0 -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -Hidden
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue   # a still-"running" old instance makes Start a no-op
    Start-Sleep -Milliseconds 500
    Start-ScheduledTask -TaskName $TaskName
    Write-Host "  $cW logon task  $cD│$cX $TaskName  $cD(running now, hidden)$cX"
    Write-Host "  $cW log         $cD│$cX $Log"
    Rule
    Write-Host "  $cT Done.$cX Log out to the character screen once so the client sees the new addon;"
    Write-Host "  after that, /reload and relog keep your settings."
    Write-Host "  $cD Remove:  & `"$dst`" -Uninstall$cX"
    Rule
    Write-Host ""
}

function Uninstall-Bridge {
    Show-Banner -Small
    Use-GameDir $(if ($GamePath) { $GamePath } else { Find-BetaDir })
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath $Seed -Recurse -Force -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath $InstallDir -Recurse -Force -ErrorAction SilentlyContinue
    Rule "removed"
    Write-Host "  $cW task        $cD│$cX $TaskName"
    Write-Host "  $cW addon       $cD│$cX $Seed"
    Write-Host "  $cW install dir $cD│$cX $InstallDir"
    Rule
    Write-Host "  Nothing else was changed. A watcher started by hand (-Watch) keeps running until you close it."
}

if ($MyInvocation.InvocationName -eq '.') { return }   # dot-sourced (tests): define only
if ($Uninstall)   { Uninstall-Bridge }
elseif ($Watch)   { Start-Watch }
else              { Install-Bridge }
